# Generated by Django 3.1.7 on 2021-03-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_contact_new_sermon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='news',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='sermon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
