# Generated by Django 3.1.7 on 2021-04-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_auto_20210331_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('about_you', models.TextField()),
            ],
        ),
    ]
