# Generated by Django 3.1.7 on 2021-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_firsttimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimer',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='firsttimer',
            name='city',
            field=models.CharField(max_length=200),
        ),
    ]
